name: build-upload
on:
  push:
    branches:
      - ID-1507
  pull_request:
    paths:
      - .github/workflows/build-okta-webhook.yml
      - 'examples/aws-lambda-okta-simple/**'

env:
  AWS_REGION: us-west-2
  S3_BUCKET: indent-artifacts-us-west-2
  INDENT_TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ARTIFACT_BUILD_TESTING_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ARTIFACT_BUILD_TESTING_AWS_SECRET_ACCESS_KEY }}
          # aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} # if you have/need it
          aws-region: ${{ env.AWS_REGION }}

      - name: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - name: Build layers (aws-lambda-okta-webhook)
        run: |
          cd examples/aws-lambda-okta-webhook/terraform-aws-okta-webhook && yarn deploy:prepare && yarn
      - name: Build function
        run: |
          cd examples/aws-lambda-okta-webhook/terraform-aws-okta-webhook && yarn build && ./scripts/build-function.sh

      # TODO: add public access
      - name: Upload to AWS S3
        run: |
          cd examples/aws-lambda-okta-simple && aws s3 cp ./dist/layers/layers.zip s3://${{ env.S3_BUCKET }}/webhooks/aws/lambda/okta-v0.0.1-canary-deps.zip --acl public-read
          aws s3 cp ./dist/function.zip s3://${{ env.S3_BUCKET }}/webhooks/aws/lambda/okta-v0.0.1-canary-function.zip --acl public-read
