name: build-auto-webhooks
on:
  push:
  pull_request:

env:
  AWS_REGION: us-west-2
  S3_BUCKET: indent-artifacts-us-west-2
  INDENT_TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ARTIFACT_BUILD_TESTING_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ARTIFACT_BUILD_TESTING_AWS_SECRET_ACCESS_KEY }}
          # aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} # if you have/need it
          aws-region: ${{ env.AWS_REGION }}

      - name: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: yarn

      - name: Create example root directory
        run: |
          mkdir -p tmp/examples
      
      - name: Create example (pagerduty)
        env:
          WEBHOOK_DIR: tmp/examples/aws-lambda-pagerduty-webhook
        run: |
          mkdir -p $WEBHOOK_DIR
          cp -r utils/* $WEBHOOK_DIR
          mv $WEBHOOK_DIR/package.example.json $WEBHOOK_DIR/package.json
          # consider moving into `utils/scripts/format-example.ts`
          # and run with `npx ts-node utils/scripts/format-example.ts $WEBHOOK_DIR`
          sed -i 's/ExampleIntegration/PagerdutyDecisionIntegration/g' $WEBHOOK_DIR/src/index.ts
          sed -i 's/# REPLACEME:vars/.../g' $WEBHOOK_DIR/variables.tf
          sed -i 's/# REPLACEME:vars/.../g' $WEBHOOK_DIR/src/index.ts

      - name: Build example (pagerduty)
        run: |
          cd tmp/examples/aws-lambda-pagerduty-webhook
          npm run build

      # TODO: add public access
      - name: Upload to AWS S3
        run: |
          cd examples/aws-lambda-tailscale-webhook && aws s3 cp ./dist/layers/layers.zip s3://${{ env.S3_BUCKET }}/webhooks/aws/lambda/tailscale-v0.0.1-canary-deps-${{ matrix.os }}-node-${{ matrix.node }}-latest.zip && aws s3 cp ./dist/layers/layers.zip s3://${{ env.S3_BUCKET }}/webhooks/aws/lambda/tailscale-v0.0.1-canary-deps-${{ matrix.os }}-node-${{ matrix.node }}-${{ env.INDENT_TAG }}.zip
          aws s3 cp ./dist/function.zip s3://${{ env.S3_BUCKET }}/webhooks/aws/lambda/tailscale-v0.0.1-canary-function-${{ matrix.os }}-node-${{ matrix.node }}-latest.zip && aws s3 cp ./dist/function.zip s3://${{ env.S3_BUCKET }}/webhooks/aws/lambda/tailscale-v0.0.1-canary-function-${{ matrix.os }}-node-${{ matrix.node }}-${{ env.INDENT_TAG }}.zip
