name: build-and-test

on:
  push:
    branches:
      - main
      - master
  pull_request:
    paths:
      - .github/workflows/build-and-test.yml
      - 'packages/**'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] 
    steps:
      - uses: actions/checkout@v2
      - name: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
          cache: yarn
      - name: deps
        run: |
          yarn
      - name: bootstrap + build
        run: |
          yarn bootstrap
      - name: test
        run: |
          yarn test