name: build-and-test

on:
  push:
    branches:
      - main
      - master
  pull_request:
    paths:
      - .github/workflows/build-and-test.yml
      - 'packages/**'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
          cache: yarn
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.5'
          cache: true
      - name: go.env
        shell: bash
        run: |
          echo "$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: go.deps
        run: |
          go mod download
      - name: deps
        run: |
          yarn
      - name: bootstrap + build
        env:
          GOPATH: "/home/runner/work/integrations/go"
        run: |
          yarn bootstrap
      - name: test
        env:
          GOPATH: "/home/runner/work/integrations/go"
        run: |
          yarn test
