name: build-upload
on:
  push:
    branches:
      - main
      - ID-1380
  pull_request:
    paths:
      - .github/workflows/build.yml
      - 'examples/aws-lambda-tailscale-simple/**'

env:
  AWS_REGION: us-west-2
  S3_BUCKET: indent-artifacts-us-west-2

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node: [12, 14, 16]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} # if you have/need it
          aws-region: ${{ env.AWS_REGION }}

      - name: Add profile credentials to ~/.aws/credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile default
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile default
          aws configure set aws_session_token ${{ secrets.AWS_SESSION_TOKEN }} --profile default

      - name: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: yarn

      - name: Build webhook (aws-lambda-tailscale-webhook)
        run: |
          yarn deploy:prepare && yarn && yarn build

      - name: Upload to AWS S3
        run: |
          aws s3 cp dist/layers/layers.zip s3://${{ env.S3_BUCKET }}/webhooks/aws/lambda/tailscale-v0.0.1-canary-deps.zip
          aws s3 cp dist/function.zip s3://${{ env.S3_BUCKET }}/webhooks/aws/lambda/tailscale-v0.0.1-canary-function.zip
